[project]
authors = ["EternalGoldenBraid <gitnicklas@pm.me>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "dyna_graph"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
manim = ">=0.18.1,<0.19"
numpy = ">=1.26.4,<2"
networkx = ">=3.4.2,<4"
plotly = ">=5.24.1,<6"
